# Generated by Django 5.2.8 on 2025-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='portions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('liters', 'л'), ('pieces', 'шт'), ('g', 'г')], max_length=20),
        ),
    ]
