# Generated by Django 5.2.8 on 2025-11-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_portions_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='portions',
            field=models.PositiveIntegerField(default=0, verbose_name='Планируемое количество порций на день'),
        ),
    ]
