# Generated by Django 5.2.8 on 2025-11-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dishingredient_quantity_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
