# Generated by Django 5.2.8 on 2025-11-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('liters', 'л'), ('ml', 'мл'), ('pieces', 'шт')], default='g', max_length=20),
        ),
    ]
